# action.yml
name: 'Remove front matter'
description: 'Remove front matter from all .md files of a directory'
inputs:
  directory:
    description: 'directory to run the action on'
    required: true
    default: 'tmp'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
